/* tslint:disable */
/* prettier-ignore */
/**
 * This file was automatically @generated by scripts/genconfig.py.
 * DO NOT MODIFY IT BY HAND. Instead, modify Config.h and run scripts/genconfig.py
 */

export interface Config {
  /** Flags to pass to slang */
  flags?: string
  /**
   * @deprecated
   * Globs of what to index. By default will index all sv and svh files in the workspace.
   */
  indexGlobs?: string[]
  /** Index configurations; by default indexes all .sv, .svh, .v, and .vh files in the workspace. */
  index?: Config__IndexConfig[]
  /**
   * @deprecated
   * Directories to exclude
   */
  excludeDirs?: string[]
  /** Thread count to use for indexing */
  indexingThreads?: number
  /** Build file to use */
  build?: string | null
  /** Build file glob pattern, e.g. `builds/{}.f`. Used for selecting build files. If omitted and no other build source is configured, defaults to matching all `.f` files in the workspace. */
  buildPattern?: string | null
  /** Whether build files use paths relative to that file */
  buildRelativePaths?: boolean
  /** Directory to treat as the effective working directory when resolving relative paths in `flags` (e.g. `-F ./my_flist.f`, `-I ../include`), mirroring `cd <workDir> && <tool> <flags>`. Relative to the workspace root; absolute paths are also accepted. Useful for ASIC flows where tools are conventionally run from a shared work directory rather than the repo root. */
  workDir?: string | null
  /** When a file that's only ever `include`d elsewhere (e.g. a `.vh`/`.svh` fragment meant to be spliced into a module body) is opened directly, analyze it in the context of the file(s) that include it instead of parsing it as a standalone top-level file. Disable to restore the previous behavior, where such files are always parsed on their own. */
  resolveIncludeFragments?: boolean
  /** Waveform file glob to open given a build. Name and top variables can be passed with {name}, {top}) */
  wavesPattern?: string | null
  /** Waveform viewer command ({} will be replaced with the WCP port), used for direct wcp connection with neovim and surfer. */
  wcpCommand?: string | null
  /** Hover behavior settings */
  hovers?: Config__HoverConfig
  /** Inline hints for things like ordered arguments, wildcard ports, and others */
  inlayHints?: Config__InlayHints
  /** Experimental / beta features. Off by default; interfaces here may change or be removed without notice. */
  experimental?: Config__Experimental
  /** Builds for direct .f selection or command-based .f generation */
  builds?: Config__Build[]
}

export interface Config__Build {
  /** Optional name used for generated build files and UI labels */
  name?: string | null
  /** Glob pattern to find files, like .f files or makefiles */
  glob?: string
  /** Optional command that produces .f content on stdout when passed the selected file */
  command?: string
}

export interface Config__Experimental {
  /** Improve analysis of UVM-style verification code. (1) Binds class-declaring .svh files (e.g. UVM component/object headers) that are `include`d inside a package, module, or similar design unit to that owner's context instead of parsing them standalone. (2) Follows virtual-interface member types and class `extends` base-class names across files when resolving a shallow compilation's dependencies. Off by default; behavior may change or be removed without notice while this is validated. */
  uvmVerificationLinting?: boolean
  /** Approximate `--single-unit` preprocessor behavior: predefine the union of all `define`s found in the build's files when parsing each file, so macros defined in one file (e.g. `uvm_macros.svh` pulled in by a package) resolve in files that don't `include` them. Symbol scoping is unchanged. Order-insensitive, so a macro defined in a later file is visible in an earlier one. Off by default. */
  singleUnitMacros?: boolean
}

export interface Config__HoverConfig {
  /** How to render leading doc comments in hovers: 'markdown' renders as markdown, 'plaintext' escapes markdown characters, 'raw' shows the comment text verbatim including comment markers. */
  docCommentFormat?: "plaintext" | "markdown" | "raw"
}

export interface Config__IndexConfig {
  /** Directories to index */
  dirs?: string[]
  /** Directories to exclude; only supports single directory names and applies to all path levels */
  excludeDirs?: string[] | null
}

export interface Config__InlayHints {
  /** Hints for port types */
  portTypes?: boolean
  /** Hints for names of ordered ports and params */
  orderedInstanceNames?: boolean
  /** Hints for port names in wildcard (.*) ports */
  wildcardNames?: boolean
  /** Function argument hints: 0=off, N=only calls with >=N args */
  funcArgNames?: number
  /** Macro argument hints: 0=off, N=only calls with >=N args */
  macroArgNames?: number
}
